server:
  port: 8080

global_filters:
  - name: logging
    enabled: true
    config:
      level: INFO

routes:
  - type: "proxy"
    path: "/api/v1/*"
    backend: "https://jsonplaceholder.typicode.com"
    filters:
      - name: authentication
        enabled: true
        config:
          required: true
      - name: rate-limiting
        enabled: true
        config:
          requests-per-minute: 100
      - name: logging
        enabled: true
        config:
          level: DEBUG

  - type: "proxy"
    path: "/foo"
    backend: "https://echo.free.beeceptor.com"
    filters:
      - name: logging
        enabled: true
        config:
          level: INFO

  - type: "proxy"
    path: "/public/*"
    backend: "https://httpbin.org"
    filters:
      - name: rate-limiting
        enabled: true
        config:
          requests-per-minute: 1000

  - type: "static"
    path: "/hello"
    response:
      status: 200
      body: "Hello, World!"
      content_type: "text/plain"
      headers:
        X-Custom-Header: "dispatch-gateway"

  - type: "static"
    path: "/status"
    response:
      status: 200
      body: '{"status": "healthy", "version": "1.0.0"}'
      content_type: "application/json"