server:
  port: 8080
  ssl:
    enabled: false

global_filters:
  - name: logging
    enabled: true
    config:
      level: INFO

routes:
  # Static health check
  - type: "static"
    path: "/health"
    response:
      status: 200
      body: "OK"
      content_type: "text/plain"

  # API routes with authentication and rate limiting
  - type: "proxy"
    path: "/api/users/*"
    backend: "http://user-service:8080"
    filters:
      - name: authentication
        enabled: true
        config:
          required: true
          skip-paths:
            - "/health"
      - name: rate-limiting
        enabled: true
        config:
          requests-per-minute: 1000

  # Public API routes
  - type: "proxy"
    path: "/public/*"
    backend: "http://public-service:8080"
    filters:
      - name: rate-limiting
        enabled: true
        config:
          requests-per-minute: 5000